{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-debug.aar",
          "url": "file_picker-0.0.1-debug.aar",
          "size": 28602,
          "sha512": "b17cc8317f83c87def7870e998f791bf42381acee66d9ba386ccf95342143a300e1dee679b732ac0256ca238a00cf2f1d7d84966fd7c4df5af604344be9e7621",
          "sha256": "df0ee0eb808b2855a75f537b2e6fced0f275ab789b0769da65df160dfe374b43",
          "sha1": "d647895729e72e67bc577285432932ce177ce64e",
          "md5": "69a2772b54660e358f3dc75ac10e5aa2"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-debug.aar",
          "url": "file_picker-0.0.1-debug.aar",
          "size": 28602,
          "sha512": "b17cc8317f83c87def7870e998f791bf42381acee66d9ba386ccf95342143a300e1dee679b732ac0256ca238a00cf2f1d7d84966fd7c4df5af604344be9e7621",
          "sha256": "df0ee0eb808b2855a75f537b2e6fced0f275ab789b0769da65df160dfe374b43",
          "sha1": "d647895729e72e67bc577285432932ce177ce64e",
          "md5": "69a2772b54660e358f3dc75ac10e5aa2"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-release.aar",
          "url": "file_picker-0.0.1-release.aar",
          "size": 27406,
          "sha512": "ffbf18a11e709054bf3ab99db23e6f3def1671bad12b224cfcb75d49eb2a1cc0f43789398c08c0399e4045a09859cca4e23393b16e8959f77a52651f188b1131",
          "sha256": "8758b9df7024570312e8213d362bb992ff614bbc823c67c13497450a7a24245a",
          "sha1": "28982c1a4cb7a7ab027f5692304684e74d919335",
          "md5": "2fa7cc898ecd178d3517198d30dc9ff3"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-release.aar",
          "url": "file_picker-0.0.1-release.aar",
          "size": 27406,
          "sha512": "ffbf18a11e709054bf3ab99db23e6f3def1671bad12b224cfcb75d49eb2a1cc0f43789398c08c0399e4045a09859cca4e23393b16e8959f77a52651f188b1131",
          "sha256": "8758b9df7024570312e8213d362bb992ff614bbc823c67c13497450a7a24245a",
          "sha1": "28982c1a4cb7a7ab027f5692304684e74d919335",
          "md5": "2fa7cc898ecd178d3517198d30dc9ff3"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-profile.aar",
          "url": "file_picker-0.0.1-profile.aar",
          "size": 27407,
          "sha512": "2d902b02c671e41cc7b431f33e319d1a9b84e2f2ced2c5582fd8857f0692324d377cac5f80342a681c8f5da6d315dd9f0e24faca116b5a110b3c5cc52e95f262",
          "sha256": "18b5ce87ecb089789f46c3560ccdbd8b44c4d9d0a1dbedcad5aaa849f0d73589",
          "sha1": "265cd2a878c12d8c3c7ef8d3ca84830fbf8a65b0",
          "md5": "d487a7038bc3863342f0ad427b612dcd"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-0.0.1-profile.aar",
          "url": "file_picker-0.0.1-profile.aar",
          "size": 27407,
          "sha512": "2d902b02c671e41cc7b431f33e319d1a9b84e2f2ced2c5582fd8857f0692324d377cac5f80342a681c8f5da6d315dd9f0e24faca116b5a110b3c5cc52e95f262",
          "sha256": "18b5ce87ecb089789f46c3560ccdbd8b44c4d9d0a1dbedcad5aaa849f0d73589",
          "sha1": "265cd2a878c12d8c3c7ef8d3ca84830fbf8a65b0",
          "md5": "d487a7038bc3863342f0ad427b612dcd"
        }
      ]
    }
  ]
}
