{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.0.1.aar",
          "url": "flutter_local_notifications_release-0.0.1.aar",
          "size": 74670,
          "sha512": "91d4078f1d7c181cf83b47b01bb462dda49dbc2ee97d25b2314b64e81b091651c921ebc2a317f5fdafa0320633a1e8249729805693140f195a6d74f12c3914b1",
          "sha256": "b711358960054538ae6a8803085d0905425cb71580ecbbb1109196af24d8146f",
          "sha1": "3f3baa3f8739089b857faab6af777c6c13348234",
          "md5": "74d78e0e36a85c87e218955e6293e7b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.0.1.aar",
          "url": "flutter_local_notifications_release-0.0.1.aar",
          "size": 74670,
          "sha512": "91d4078f1d7c181cf83b47b01bb462dda49dbc2ee97d25b2314b64e81b091651c921ebc2a317f5fdafa0320633a1e8249729805693140f195a6d74f12c3914b1",
          "sha256": "b711358960054538ae6a8803085d0905425cb71580ecbbb1109196af24d8146f",
          "sha1": "3f3baa3f8739089b857faab6af777c6c13348234",
          "md5": "74d78e0e36a85c87e218955e6293e7b2"
        }
      ]
    }
  ]
}
