{
  "formatVersion": "1.1",
  "component": {
    "group": "be.tramckrijte.workmanager",
    "module": "workmanager_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "workmanager_release-0.0.1.aar",
          "url": "workmanager_release-0.0.1.aar",
          "size": 64390,
          "sha512": "edafbb32ab151b2439dbcf7c256f4473c770a78ed3ca9db017c95a1c3c089c055e57ad1c542a588954a3e69e63bf4f7e2b8a51bb9663220b7337781fe099de8d",
          "sha256": "f0f3e9cec338a66e8c00b43ca2cbc352cfadfcbe0c354406f9250672f9ec6d70",
          "sha1": "dacff28376d635889781f5bbfc2cb8863bb6c516",
          "md5": "e83f447a60c4913e18150266dad08407"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "workmanager_release-0.0.1.aar",
          "url": "workmanager_release-0.0.1.aar",
          "size": 64390,
          "sha512": "edafbb32ab151b2439dbcf7c256f4473c770a78ed3ca9db017c95a1c3c089c055e57ad1c542a588954a3e69e63bf4f7e2b8a51bb9663220b7337781fe099de8d",
          "sha256": "f0f3e9cec338a66e8c00b43ca2cbc352cfadfcbe0c354406f9250672f9ec6d70",
          "sha1": "dacff28376d635889781f5bbfc2cb8863bb6c516",
          "md5": "e83f447a60c4913e18150266dad08407"
        }
      ]
    }
  ]
}
