{
  "formatVersion": "1.1",
  "component": {
    "group": "be.tramckrijte.workmanager",
    "module": "workmanager_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "workmanager_debug-0.0.1.aar",
          "url": "workmanager_debug-0.0.1.aar",
          "size": 66933,
          "sha512": "de588633ec58b8fdf4006f1ddf8a8a685f15497bc48e9836fdf56add812b6fc53c27105280cdeadd8a128ebdf5f80e811a515c1c99ec4e1d49d5484611b43b98",
          "sha256": "cf859152b71ac30c53d4238b7b20ca396cc767e125e1366d4983d70c780b4a85",
          "sha1": "1367734a7e5b0004b7e812939bc1ddf66025e968",
          "md5": "b5164f9e340d47e345fdd6f299638336"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "workmanager_debug-0.0.1.aar",
          "url": "workmanager_debug-0.0.1.aar",
          "size": 66933,
          "sha512": "de588633ec58b8fdf4006f1ddf8a8a685f15497bc48e9836fdf56add812b6fc53c27105280cdeadd8a128ebdf5f80e811a515c1c99ec4e1d49d5484611b43b98",
          "sha256": "cf859152b71ac30c53d4238b7b20ca396cc767e125e1366d4983d70c780b4a85",
          "sha1": "1367734a7e5b0004b7e812939bc1ddf66025e968",
          "md5": "b5164f9e340d47e345fdd6f299638336"
        }
      ]
    }
  ]
}
