{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.0.1.aar",
          "url": "flutter_local_notifications_debug-0.0.1.aar",
          "size": 79045,
          "sha512": "6f976a2a0e80f45a654724d7b41b029b78766a44be406a51bfcde801076dcf0c82aef94e0ed4f184235d9f349b8215ddcf46bd03326f9df06d8afca5b3733820",
          "sha256": "76a4a4605fc1fb7420ff58ddeacab9c8163814354673d5f76ba42a99aa70c61f",
          "sha1": "1e7311189095cab69c454f27d7313a75d2398368",
          "md5": "a8d239ba604f635b6212b808022c8690"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.0.1.aar",
          "url": "flutter_local_notifications_debug-0.0.1.aar",
          "size": 79045,
          "sha512": "6f976a2a0e80f45a654724d7b41b029b78766a44be406a51bfcde801076dcf0c82aef94e0ed4f184235d9f349b8215ddcf46bd03326f9df06d8afca5b3733820",
          "sha256": "76a4a4605fc1fb7420ff58ddeacab9c8163814354673d5f76ba42a99aa70c61f",
          "sha1": "1e7311189095cab69c454f27d7313a75d2398368",
          "md5": "a8d239ba604f635b6212b808022c8690"
        }
      ]
    }
  ]
}
