{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.1.aar",
          "url": "flutter_secure_storage_release-0.0.1.aar",
          "size": 26455,
          "sha512": "7ff86f99abd6f0f916233e74cfe7cedcff3de055b3a2f82291deabc9c6ee6b667fea139033d86a6ac138dd22de5d71f1ddef9a44489562f93fc9f7d8c482e8e3",
          "sha256": "92c2c39c104f07b65f3aec2cc078c01303e20b9fa4641cd16e0c132fbf8fe957",
          "sha1": "7cbb1c1f193e9e6c8961c396a9dd02eb8e839e98",
          "md5": "3bf43af6624bc17d311e958618a512a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-0.0.1.aar",
          "url": "flutter_secure_storage_release-0.0.1.aar",
          "size": 26455,
          "sha512": "7ff86f99abd6f0f916233e74cfe7cedcff3de055b3a2f82291deabc9c6ee6b667fea139033d86a6ac138dd22de5d71f1ddef9a44489562f93fc9f7d8c482e8e3",
          "sha256": "92c2c39c104f07b65f3aec2cc078c01303e20b9fa4641cd16e0c132fbf8fe957",
          "sha1": "7cbb1c1f193e9e6c8961c396a9dd02eb8e839e98",
          "md5": "3bf43af6624bc17d311e958618a512a0"
        }
      ]
    }
  ]
}
