{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-0.0.1.aar",
          "url": "file_picker_debug-0.0.1.aar",
          "size": 28366,
          "sha512": "21aa13fe6ec2089dc9496a50c214731f1c827c1257d45a9d8df88060df039f26a68cb692b961821621205c1663afbab8568384f6e5d04f0548720a2b090a3e75",
          "sha256": "a8d2042839293425af5997a8fedb1ea892bfe1781c6300e226471ba8209e43b8",
          "sha1": "e171246686e75ffc8c02401e041ec0be87d14c10",
          "md5": "975a6850aeca53d409f088360592c35b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-0.0.1.aar",
          "url": "file_picker_debug-0.0.1.aar",
          "size": 28366,
          "sha512": "21aa13fe6ec2089dc9496a50c214731f1c827c1257d45a9d8df88060df039f26a68cb692b961821621205c1663afbab8568384f6e5d04f0548720a2b090a3e75",
          "sha256": "a8d2042839293425af5997a8fedb1ea892bfe1781c6300e226471ba8209e43b8",
          "sha1": "e171246686e75ffc8c02401e041ec0be87d14c10",
          "md5": "975a6850aeca53d409f088360592c35b"
        }
      ]
    }
  ]
}
