{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-0.0.1.aar",
          "url": "flutter_secure_storage_debug-0.0.1.aar",
          "size": 27756,
          "sha512": "8509a1e464264bbbd69d11ef68ce4b5cdcb7623fb4fe7962dbffd37e1740b7aeff4aa227a5341ea5197f8293460dddf1b589c3d9a594eb1103501c1a67f865e7",
          "sha256": "755fa56d125ba92575d855003cc2e1630f2dabbfc003c866c971c0bb635cdc07",
          "sha1": "d14b08800cf19af429c49e6589f150bc6ab781d4",
          "md5": "1110f4672a57e3a1fec2522dda79bd9e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-0.0.1.aar",
          "url": "flutter_secure_storage_debug-0.0.1.aar",
          "size": 27756,
          "sha512": "8509a1e464264bbbd69d11ef68ce4b5cdcb7623fb4fe7962dbffd37e1740b7aeff4aa227a5341ea5197f8293460dddf1b589c3d9a594eb1103501c1a67f865e7",
          "sha256": "755fa56d125ba92575d855003cc2e1630f2dabbfc003c866c971c0bb635cdc07",
          "sha1": "d14b08800cf19af429c49e6589f150bc6ab781d4",
          "md5": "1110f4672a57e3a1fec2522dda79bd9e"
        }
      ]
    }
  ]
}
