{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-debug.aar",
          "url": "flutter_secure_storage-0.0.1-debug.aar",
          "size": 18263,
          "sha512": "9912f4b3fe23f5d6e1b80c52be6a4cd1131a4bc1065a51c6c4aa1d06cb307f23128a669cb346f406c5e11b743879b807add92da2d58f01ad6bbebb87b943605e",
          "sha256": "a468977118a3ffa5abb972f5e898be9f602050cead84d2dc7c9f7d4c5acd0a63",
          "sha1": "769d3e3059f8e1ff95846f533d22af0e700a6f7b",
          "md5": "132ac75914ac07d6fc354b22924786f7"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-debug.aar",
          "url": "flutter_secure_storage-0.0.1-debug.aar",
          "size": 18263,
          "sha512": "9912f4b3fe23f5d6e1b80c52be6a4cd1131a4bc1065a51c6c4aa1d06cb307f23128a669cb346f406c5e11b743879b807add92da2d58f01ad6bbebb87b943605e",
          "sha256": "a468977118a3ffa5abb972f5e898be9f602050cead84d2dc7c9f7d4c5acd0a63",
          "sha1": "769d3e3059f8e1ff95846f533d22af0e700a6f7b",
          "md5": "132ac75914ac07d6fc354b22924786f7"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-release.aar",
          "url": "flutter_secure_storage-0.0.1-release.aar",
          "size": 17434,
          "sha512": "5da29e2b82d19294682a72c5bea713fcfa480129d855248d9b12b016eac35d5bde14dfc40824d1a3f25f3ec8811229ce4670dd2edb0563fe77693b2c6f0de936",
          "sha256": "0e696c7fbc3d12b032837dfc08783820754ce695a213a4d1e47268d0ed9b9edb",
          "sha1": "52f82c84a43700db2bb7674c82108436ad324149",
          "md5": "a1469c84fc345743a25958837bc34d28"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-release.aar",
          "url": "flutter_secure_storage-0.0.1-release.aar",
          "size": 17434,
          "sha512": "5da29e2b82d19294682a72c5bea713fcfa480129d855248d9b12b016eac35d5bde14dfc40824d1a3f25f3ec8811229ce4670dd2edb0563fe77693b2c6f0de936",
          "sha256": "0e696c7fbc3d12b032837dfc08783820754ce695a213a4d1e47268d0ed9b9edb",
          "sha1": "52f82c84a43700db2bb7674c82108436ad324149",
          "md5": "a1469c84fc345743a25958837bc34d28"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-profile.aar",
          "url": "flutter_secure_storage-0.0.1-profile.aar",
          "size": 17432,
          "sha512": "4bf823fa4e686230dec511781a427de0085619833a781307eb0a220fb08dcb66d8d2486b86a04763ac4d2ec5040dd9445a3c62a758f487c85034dd169a4ba91f",
          "sha256": "1eac9d66bfb60e99940b93027ae79abda627bc9bae3906a649a8e3649017164e",
          "sha1": "ec90477769176307723e3b000e12fa26f4cfa6ac",
          "md5": "93be11ca749a7314d79338d4cec95855"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage-0.0.1-profile.aar",
          "url": "flutter_secure_storage-0.0.1-profile.aar",
          "size": 17432,
          "sha512": "4bf823fa4e686230dec511781a427de0085619833a781307eb0a220fb08dcb66d8d2486b86a04763ac4d2ec5040dd9445a3c62a758f487c85034dd169a4ba91f",
          "sha256": "1eac9d66bfb60e99940b93027ae79abda627bc9bae3906a649a8e3649017164e",
          "sha1": "ec90477769176307723e3b000e12fa26f4cfa6ac",
          "md5": "93be11ca749a7314d79338d4cec95855"
        }
      ]
    }
  ]
}
