{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ivo.sociomile_mobile_sdk",
    "module": "flutter_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "be.tramckrijte.workmanager",
          "module": "workmanager",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.1.aar",
          "url": "flutter_release-0.0.1.aar",
          "size": 12640592,
          "sha512": "8ef97cdd93abcaef9587d8f8eac48a0985f69ff961ea73f322966061f00adb227753b5720bfb84ccc1da0ff75cf6eb185cd08ff506b505135eb8253c2c07eba9",
          "sha256": "e8c2d3764f2197ffe0a52a1f704fdf80c9d52f965e2e1cf0f764226d960fdfb0",
          "sha1": "5e764b31072c1637b3a380f818e4b527fb80d8e7",
          "md5": "e9b2441e9c368abfdd64948e5f8cb856"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "be.tramckrijte.workmanager",
          "module": "workmanager",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity_plus",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.0.1.aar",
          "url": "flutter_release-0.0.1.aar",
          "size": 12640592,
          "sha512": "8ef97cdd93abcaef9587d8f8eac48a0985f69ff961ea73f322966061f00adb227753b5720bfb84ccc1da0ff75cf6eb185cd08ff506b505135eb8253c2c07eba9",
          "sha256": "e8c2d3764f2197ffe0a52a1f704fdf80c9d52f965e2e1cf0f764226d960fdfb0",
          "sha1": "5e764b31072c1637b3a380f818e4b527fb80d8e7",
          "md5": "e9b2441e9c368abfdd64948e5f8cb856"
        }
      ]
    }
  ]
}
