{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-debug.aar",
          "url": "sqflite-0.0.1-debug.aar",
          "size": 38132,
          "sha512": "361c38318b71251bd2f55521dd550b42f422a7f2fe33e8375c00745c078116289fef75d88451f0573aedfe25ddee549e9a77f952f24d480ee349e7e93f54e6b5",
          "sha256": "612ec44ab6a445f6070e3d003f880823cb314e09c1f23d516249914259accc37",
          "sha1": "1824a0fb69dcf9b2ea1fb18513095d040dc7abb9",
          "md5": "b86554475959b8bbce940c4894ffd099"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-debug.aar",
          "url": "sqflite-0.0.1-debug.aar",
          "size": 38132,
          "sha512": "361c38318b71251bd2f55521dd550b42f422a7f2fe33e8375c00745c078116289fef75d88451f0573aedfe25ddee549e9a77f952f24d480ee349e7e93f54e6b5",
          "sha256": "612ec44ab6a445f6070e3d003f880823cb314e09c1f23d516249914259accc37",
          "sha1": "1824a0fb69dcf9b2ea1fb18513095d040dc7abb9",
          "md5": "b86554475959b8bbce940c4894ffd099"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-release.aar",
          "url": "sqflite-0.0.1-release.aar",
          "size": 36310,
          "sha512": "b6f4e22694dd62abde1ae2a5bda3a51712fe5bc12643b2555cd104dcae822b68a6ec74b581fbfc84199c37da304df06633fc8cc20662209a4a3fdbacd57d7640",
          "sha256": "5f706674feb21bc0c744f30cf02b4bd1786b50fcfcd114216cbfe245dcfb308b",
          "sha1": "a3ae39f6279d4a04f9dd7e92bcc00bb2e6d5bd47",
          "md5": "f9a3967548cb4c56d7e1b447da0d32d3"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-release.aar",
          "url": "sqflite-0.0.1-release.aar",
          "size": 36310,
          "sha512": "b6f4e22694dd62abde1ae2a5bda3a51712fe5bc12643b2555cd104dcae822b68a6ec74b581fbfc84199c37da304df06633fc8cc20662209a4a3fdbacd57d7640",
          "sha256": "5f706674feb21bc0c744f30cf02b4bd1786b50fcfcd114216cbfe245dcfb308b",
          "sha1": "a3ae39f6279d4a04f9dd7e92bcc00bb2e6d5bd47",
          "md5": "f9a3967548cb4c56d7e1b447da0d32d3"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-profile.aar",
          "url": "sqflite-0.0.1-profile.aar",
          "size": 36313,
          "sha512": "3fe67860ab98c0a46ca68cdb8206c6603819849cd9a073d55b9019c034c0bf7bb08e123a23d39d8a4bced4b51c871e7af277be6dfedcf46601c61b15e9540215",
          "sha256": "77a6d747f4035f37bce317a093cc7ef8d56180e59f395b0283e8b94b3ccb516f",
          "sha1": "b2bf1ca9d1a617438ef33ee455dab3e00b5e6c69",
          "md5": "5c68c8e495bac711716b979dba7c159c"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite-0.0.1-profile.aar",
          "url": "sqflite-0.0.1-profile.aar",
          "size": 36313,
          "sha512": "3fe67860ab98c0a46ca68cdb8206c6603819849cd9a073d55b9019c034c0bf7bb08e123a23d39d8a4bced4b51c871e7af277be6dfedcf46601c61b15e9540215",
          "sha256": "77a6d747f4035f37bce317a093cc7ef8d56180e59f395b0283e8b94b3ccb516f",
          "sha1": "b2bf1ca9d1a617438ef33ee455dab3e00b5e6c69",
          "md5": "5c68c8e495bac711716b979dba7c159c"
        }
      ]
    }
  ]
}
