{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-0.0.1.aar",
          "url": "file_picker_release-0.0.1.aar",
          "size": 27189,
          "sha512": "27418ccc9b4e0c1dc0c452026d1f3d70a00b818715b36ff9edc32c94562a813fca88f9ed0ff2638c2913627304110214a1f1e884f6cf9dec666fefac1b2407b1",
          "sha256": "30204d1185c575db29de40cebc5be8a115a617766cfe408d2ff802e50c19454a",
          "sha1": "89264ebc7bb2ff8513b294bf4c02d63703c94256",
          "md5": "6111fc2d4f8ed542822614bf4672d4b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-0.0.1.aar",
          "url": "file_picker_release-0.0.1.aar",
          "size": 27189,
          "sha512": "27418ccc9b4e0c1dc0c452026d1f3d70a00b818715b36ff9edc32c94562a813fca88f9ed0ff2638c2913627304110214a1f1e884f6cf9dec666fefac1b2407b1",
          "sha256": "30204d1185c575db29de40cebc5be8a115a617766cfe408d2ff802e50c19454a",
          "sha1": "89264ebc7bb2ff8513b294bf4c02d63703c94256",
          "md5": "6111fc2d4f8ed542822614bf4672d4b6"
        }
      ]
    }
  ]
}
