{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.1.aar",
          "url": "sqflite_release-0.0.1.aar",
          "size": 37560,
          "sha512": "34e596fd6c73113a599466a3faae6b121c9380e6356598e16d8034eaa3df681f633f6f1cd7966749e5390355a1f353d9e3969519f102b2e8631d1c9f383d4dd7",
          "sha256": "60e7bdb40d342014cf57fa81d9661c6d388cb53ae396d684e460dca6764e3614",
          "sha1": "194d06cac1c6d33f66f0ba48b6e571719456807e",
          "md5": "ea0372dcc01af33d7187b79a84700a8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-5c984c26ebc4a0a8897305d3c6bef70ced91090d"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-0.0.1.aar",
          "url": "sqflite_release-0.0.1.aar",
          "size": 37560,
          "sha512": "34e596fd6c73113a599466a3faae6b121c9380e6356598e16d8034eaa3df681f633f6f1cd7966749e5390355a1f353d9e3969519f102b2e8631d1c9f383d4dd7",
          "sha256": "60e7bdb40d342014cf57fa81d9661c6d388cb53ae396d684e460dca6764e3614",
          "sha1": "194d06cac1c6d33f66f0ba48b6e571719456807e",
          "md5": "ea0372dcc01af33d7187b79a84700a8a"
        }
      ]
    }
  ]
}
